#!/usr/bin/python
import argparse
import uuid
import json
import os

parser = argparse.ArgumentParser(description="Generates a new key-user pair and writes it to the keyfile")
parser.add_argument("-n", "--name", type=str, required=True)
parser.add_argument("-f", "--file", type=str, default="keys.json")

args = parser.parse_args()

def get_user_file(path):
    try:
        return open(path, "r+")
    except:
        return None

def register_new(name, dictionary):
    key = str(uuid.uuid4())
    dictionary[key] = name
    return key

def add_new_user():
    with get_user_file(args.file) as userfile:
        if userfile == None:
            print("Error: could not open {}".format(args.file))
            return
        
        userkeys = None
        try:
            userkeys = json.load(userfile)
        except:
            if os.path.getsize(userfile.name) > 0:
                print("Error: could not parse JSON in {} and file is not empty".format(args.file))
                return
            else:
                userkeys = {}
        
        newkey = register_new(args.name, userkeys)

        userfile.seek(0)
        userfile.write(json.dumps(userkeys))
        userfile.truncate()

        print("Added user '{}' with key '{}'".format(args.name, newkey))

add_new_user()