#!/usr/bin/python
import argparse
import uuid
import json
import os

parser = argparse.ArgumentParser(description="Lists ")
parser.add_argument("-n", "--name", type=str)
parser.add_argument("-f", "--file", type=str, default="keys.json")

args = parser.parse_args()

def get_user_file(path):
    try:
        return open(path, "r")
    except:
        return None

def list_keys():
    with get_user_file(args.file) as userfile:
        if userfile == None:
            print("Error: could not open {}".format(args.file))
            return
        
        userkeys = None
        try:
            userkeys = json.load(userfile)
        except:
            print("Error: could not parse JSON in {}".format(args.file))
            return

        if userkeys == None:
            userkeys = {}

        for key in userkeys.keys():
            print("{}:{}".format(key, userkeys[key]))

list_keys()