#!/usr/bin/python
import argparse
import uuid
import json

parser = argparse.ArgumentParser(description="Generates a new key-user pair and write it to a target keyfile")
parser.add_argument("-n", "--name", type=str)
parser.add_argument("-f", "--file", type=str)

args = parser.parse_args()

users = None
with open(args.file, "r") as userfile:
    users = json.load(userfile)
    users.pop(args.name)

if not users == None:
    with open(args.file, "w") as userfile:
        userfile.write(json.dumps(users))
    print("Done.")
else:
    print("Failed.")